# -----------------------------------------------------------------------------
# run_all.R  --  master script: runs the entire analysis end-to-end
# Zan Merrill, Andy Kim, Thomas Garner  |  OM 386 Spring 2026
#
# Usage from the repository root:
#   Rscript R/run_all.R
#
# Sources the four pipeline scripts in dependency order. No analysis code
# is duplicated here; each script remains the single source of truth for
# its stage. If you edit 02_cluster.R, you do not edit this file too.
# -----------------------------------------------------------------------------

t.start = Sys.time()

cat("\n=== Step 1: PCA construct scores =============================\n")
source("R/01_pca.R")

cat("\n=== EDA: summary stats, correlations, item distributions ====\n")
source("R/00_eda.R")

cat("\n=== Step 2: clustering (mclust + hand-coded EM) =============\n")
source("R/02_cluster.R")

cat("\n=== Step 3: Bayesian hierarchical Gibbs + lmer cross-check ==\n")
source("R/03_bayes_hlm.R")

t.elapsed = difftime(Sys.time(), t.start, units="secs")
cat(sprintf("\n=== Done. Total wall time: %.1f seconds ===\n",
            as.numeric(t.elapsed)))
cat("Outputs are in data/processed/, output/tables/, ",
    "output/figures/, and output/diagnostics/.\n", sep="")
